# Generated by Django 4.2.3 on 2026-08-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_choice_submission_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='context',
            new_name='content',
        ),
    ]
